name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    paths-ignore:
      - "**/*.md"
    tags:
      - "v*.*.**"
    branches:
      - "main"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jakobmoellerdev/topovgm
  IMAGE_ARTIFACT: topovgm-ci-container-image
jobs:
  image:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/s390x
          - linux/ppc64le
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: ${{ matrix.platform }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Resolve Buildcache
        id: buildcache
        run: |
          BUILDCACHE_SUFFIX=${{ matrix.platform }}
          BUILDCACHE_SUFFIX=${BUILDCACHE_SUFFIX//\//-}
          echo "BUILDCACHE_SUFFIX=${BUILDCACHE_SUFFIX}" >> $GITHUB_ENV
      - name: Build and export
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          provenance: true
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ env.BUILDCACHE_SUFFIX }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ env.BUILDCACHE_SUFFIX }},mode=max
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
    outputs:
      meta: ${{ steps.meta.outputs.json }}
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      annotations: ${{ steps.meta.outputs.annotations }}

  image-merge:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs:
      - image
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} 

  unit-tests:
    env:
      GOTOOLCHAIN: local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Run tests
        run: sudo make test

  e2e-minikube:
    needs: image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-

      - name: install dependencies of minikube
        env:
          CNI_PLUGINS_VERSION: v1.5.1
          CRI_DOCKERD_VERSION: v0.3.14
          CRICTL_VERSION: v1.30.1
        run: |
          curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/${{ env.CNI_PLUGINS_VERSION }}/cni-plugins-linux-amd64-${{ env.CNI_PLUGINS_VERSION }}.tgz
          sudo mkdir -p /opt/cni/bin
          sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz

          # Install cri-docker
          git clone -n https://github.com/Mirantis/cri-dockerd
          cd cri-dockerd
          git checkout ${{ env.CRI_DOCKERD_VERSION }}
          mkdir bin
          go get && go build -o bin/cri-dockerd
          mkdir -p /usr/local/bin
          sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
          sudo cp -a packaging/systemd/* /etc/systemd/system
          sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service

          # This is a workaround for the following issue.
          # https://github.com/kubernetes/minikube/issues/15265
          sudo ln -s /usr/local/bin/cri-dockerd /usr/bin/cri-dockerd

          sudo systemctl daemon-reload
          sudo systemctl enable cri-docker.service
          sudo systemctl enable --now cri-docker.socket
          curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/${{ env.CRICTL_VERSION }}/crictl-${{ env.CRICTL_VERSION }}-linux-amd64.tar.gz --output crictl-${{ env.CRICTL_VERSION }}-linux-amd64.tar.gz
          sudo tar zxvf crictl-${{ env.CRICTL_VERSION }}-linux-amd64.tar.gz -C /usr/local/bin
      - run: make -C test/e2e setup
      - run: make -C test/e2e launch

      - name: determine node
        id: nodename
        run: |
          echo "node=$(kubectl get node -oyaml | yq -r .items[0].metadata.name)" >> $GITHUB_OUTPUT
      - name: set node name on sample
        uses: mikefarah/yq@master
        with:
          cmd: yq -i -e '.spec.nodeName = "${{ steps.nodename.outputs.node }}"' config/samples/topolvm_v1alpha1_volumegroup.yaml
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Load image into Docker
        run: |
          docker load --input ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          docker image ls -a
      - name: Setup Loop Device
        run: |
          export DEVICE=5
          dd if=/dev/zero of=/tmp/lblock$DEVICE bs=4K count=262144
          sudo losetup /dev/loop$DEVICE /tmp/lblock$DEVICE
          echo "Using loop device /dev/loop$DEVICE"
      - run: make test-e2e
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}


  e2e-k3d:
    env:
      K3D_NODE_IMAGE: ghcr.io/jakobmoellerdev/k3s:alpine-latest
    needs: image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Create k3d cluster with Flannel
        run: |
          k3d cluster create \
            --image ${{ env.K3D_NODE_IMAGE }} \
            --k3s-arg "--disable=traefik@server:*" \
            --k3s-arg "--disable=servicelb@server:*" \
            --k3s-arg "--node-name=test-node"@server:0 \
            --no-lb \
            --no-rollback \
            --volume /dev:/dev
      - name: Access loop device from nodes
        run: |
          docker exec $(k3d node list -o yaml | yq -r '.[0].name') ls /dev/loop*
          docker exec $(k3d node list -o yaml | yq -r '.[0].name') sh -c 'export DEVICE=5 && dd if=/dev/zero of=/tmp/lblock$DEVICE bs=4K count=262144 && losetup /dev/loop$DEVICE /tmp/lblock$DEVICE && echo "Using loop device /dev/loop$DEVICE"'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Load image
        run: |
          k3d image import ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}

      - name: determine node
        id: nodename
        run: |
          echo "node=$(kubectl get node -oyaml | yq -r .items[0].metadata.name)" >> $GITHUB_OUTPUT
      - name: set node name on sample
        uses: mikefarah/yq@master
        with:
          cmd: yq -i -e '.spec.nodeName = "${{ steps.nodename.outputs.node }}"' config/samples/topolvm_v1alpha1_volumegroup.yaml

      - run: make test-e2e
        env:
          IMAGE_NAME:${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}